Repository KNU-HAEDAL/Haedal-Rental-BE, pull requests merged in 2025-03, with the labels that each got.

#9 [기능 구현] 로그인 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/rental/haedal/auth/controller/AuthController.java
  src/main/java/com/rental/haedal/auth/domain/Member.java
  src/main/java/com/rental/haedal/auth/domain/MemberRepository.java
  src/main/java/com/rental/haedal/auth/domain/MemberType.java
  src/main/java/com/rental/haedal/auth/service/AuthFilter.java
  src/main/java/com/rental/haedal/auth/service/AuthService.java
  src/main/java/com/rental/haedal/auth/service/AuthUtil.java
  src/main/java/com/rental/haedal/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature, 📡 API

#11 [개발 환경] Swagger API 수정
  build.gradle
  src/main/java/com/rental/haedal/admin/controller/AdminController.java
  src/main/java/com/rental/haedal/admin/dto/req/AdminAddItemRequest.java
  src/main/java/com/rental/haedal/admin/dto/req/AdminItemRequest.java
  src/main/java/com/rental/haedal/auth/domain/Member.java
  src/main/java/com/rental/haedal/auth/dto/req/SignUpRequest.java
  src/main/java/com/rental/haedal/auth/service/AuthService.java
  src/main/java/com/rental/haedal/config/SwaggerConfig.java
  src/main/java/com/rental/haedal/rental/controller/RentalController.java
  src/main/java/com/rental/haedal/rental/dto/req/ItemListRequest.java
  src/main/java/com/rental/haedal/rental/dto/res/ItemResponse.java
  src/main/java/com/rental/haedal/rental/dto/res/UserRentalResponse.java
  src/main/resources/application.yml
Labels: 📦 Environment, 📡 API

#13 [기능 구현] 토큰에서 유저 정보 확인 기능
  src/main/java/com/rental/haedal/auth/domain/MemberRepository.java
  src/main/java/com/rental/haedal/auth/domain/MemberUserDetails.java
  src/main/java/com/rental/haedal/auth/service/AuthFilter.java
  src/main/java/com/rental/haedal/auth/service/AuthService.java
  src/main/java/com/rental/haedal/auth/service/AuthUtil.java
Labels: ✨ Feature
